name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: nateraw/huggingface-sync-action@v1
        with:
          github_repo_id: shubhamchimkar/Medical-Chatbot
          huggingface_repo_id: Monster10/medical-chatbot
          repo_type: space
          token: ${{ secrets.HF_TOKEN }}
